[phases.setup]
nixPkgs = ["python311", "gcc", "ffmpeg", "espeak-ng", "libsndfile"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port 3000"
